// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vzpbqulsiseapacbkrhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6cGJxdWxzaXNlYXBhY2JrcmhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MzUzNDEsImV4cCI6MjA4NDExMTM0MX0.C0fCt7hiSFjdV7INwCiy4yU8qHfyZ8Dmfh9_8V6qSu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);